### ISSUE TITLE
Bug: Add FLAG_(IM)MUTABLE for pending intents in A12+

### ISSUE THREAD

**Issue by proItheus** [appml/neutrinote#44] opened 2022-09-09 07:33 UTC
A12+ requires FLAG_(IM)MUTABLE for all pending intents. Now the app will throw an error when creating widgets.

**Comment by appml** [comment] 2022-09-09 15:35
Hmmm... Can't reproduce the error on A12+ on multiple launchers.  Any info about your launcher?  Tired remove and re-add the widget?

**Comment by proItheus** [comment] 2022-09-09 16:15
Ahh, my fault. The `note browser` widget works fine , while `new note` widget throws an error.

**Comment by appml** [comment] 2022-09-10 22:36
Should have been fixed in the next build (v4.2.4)

**Comment by appml** [comment] 2022-12-27 02:48
Resolved.

**Closed by appml** 2022-12-27 02:48 UTC
