### ISSUE TITLE
Cursor is always rendered

### ISSUE THREAD

**Issue by SIRSteiner** [appml/neutrinote#25] opened 2022-02-12 11:15 UTC
Please look at the screenshot.
![IMG_20220212_120839](https://user-images.githubusercontent.com/3488638/153709079-f9c026b3-eafa-4196-a85a-130af655b39f.jpg)

**Comment by appml** [comment] 2022-02-12 16:12
> Please look at the screenshot. ![IMG_20220212_120839](https://user-images.githubusercontent.com/3488638/153709079-f9c026b3-eafa-4196-a85a-130af655b39f.jpg)

Reason for closing: the cursor is for retaining scrolling position in Markdown rendering.  Therefore not a bug.

**Closed by appml** 2022-02-12 16:12 UTC
